### ISSUE TITLE
[Warp.Http 0.15.3] SourceGenerator throws KeyNotFoundException 'BindingTarget' on PUT/DELETE attributes and on POST commands without explicit [FromBody]

### ISSUE THREAD

**Issue by domagojmedo** [moberghr/jobly#208]
## Versions
- `Moberg.Warp.Http` 0.15.3 (also `Warp.Core` / `Warp.Provider.SqlServer` / `Warp.UI` 0.15.3)
- `net10.0`, .NET SDK 10.0.x
- Build environment: Windows 11, Rider + `dotnet build` from CLI

## Symptom

A single warning at build time and no errors:

```
CSC : warning CS8785: Generator 'WarpHttpGenerator' failed to generate source.
It will not contribute to the output and compilation errors may occur as a result.
Exception was of type 'KeyNotFoundException' with message
'The given key 'Warp.Http.SourceGenerator.BindingTarget' was not present in the dictionary.'
```

Because the generator bails out silently, **none** of the `[WarpHttp*]` route mappings in the assembly get emitted. `MapWarpHttp()` returns zero endpoints — every call hits a 404. The build "succeeds" with 0 errors, so this is easy to miss in CI.

### 1. `[WarpHttpPut]` and `[WarpHttpDelete]` attributes

Any handler decorated with these attributes trips the generator:

```csharp
public sealed record DeleteFoo([FromRoute] int Id) : IRequest<OkResponse>;

[WarpHttpDelete("/api/foo/{id}")]   // <- crashes the generator
public sealed class DeleteFooHandler : IRequestHandler<DeleteFoo, OkResponse>
{
    public Task<OkResponse> HandleAsync(DeleteFoo r, CancellationToken ct) => ...;
}
```

Both `WarpHttpPutAttribute` and `WarpHttpDeleteAttribute` exist in the shipped `Warp.Http.dll` (confirmed via reflection on the assembly), so it looks like the source generator just isn't wired to handle these two `BindingTarget` cases.

### 2. POST command with multiple top-level parameters

```csharp
public sealed record CreateFoo(string Name, decimal Price, List<int> Tags)   // <- crashes
    : IRequest<FooDto>;

[WarpHttpPost("/api/foo")]
public sealed class CreateFooHandler : IRequestHandler<CreateFoo, FooDto> { ... }
```

### 3. POST command with a single non-`[FromBody]` parameter

This pattern works in 0.14.1 (it's the same shape as `LoginCommand(string Password)` in known consumers) but **regresses** in 0.15.3:

```csharp
public sealed record LoginCommand(string Password) : IRequest<OkResponse>;  // <- crashes in 0.15.3

[WarpHttpPost("/api/auth/login")]
public sealed class LoginHandler : IRequestHandler<LoginCommand, OkResponse> { ... }
```

## Expected

- `[WarpHttpPut]` / `[WarpHttpDelete]` should emit routes the same way `[WarpHttpGet]` / `[WarpHttpPost]` do.
- POST commands with any combination of `[FromRoute]` + scalar body params should be valid (or, if there's a documented requirement to use `[FromBody]`, the analyzer should surface a diagnostic, not a silent generator crash).
- A generator that can't handle an input should emit a `Diagnostic` (`error WARP00xx: ...`), not throw `KeyNotFoundException` and produce no output.

## Workaround

Every POST/mutation currently has to look like this:

```csharp
public sealed record CreateFooBody(string Name, decimal Price, List<int> Tags);
public sealed record CreateFooCommand([FromBody] CreateFooBody Body) : IRequest<FooDto>;

[WarpHttpPost("/api/foo")]              // <- works
[WarpHttpPost("/api/foo/{id}/delete")]  // <- POST instead of DELETE, also works
```

i.e. **every** POST command pairs `[FromRoute]` route params with an explicit `[FromBody]` sub-record, and PUT/DELETE are rewritten as POST with a `/delete` (or similar) action suffix.

## Suggested fix direction

It looks like `Warp.Http.SourceGenerator` builds a dictionary of `BindingTarget` values during analysis and then looks them up by some shape it doesn't always populate. From the symptom set:

- Add `BindingTarget` entries for `WarpHttpPut` / `WarpHttpDelete`.
- When a POST command parameter has neither `[FromRoute]` nor `[FromQuery]`, default to the same path 0.14.1 used (treat as body) instead of failing the lookup. Or surface a diagnostic instructing the user to add `[FromBody]`.

Happy to provide a minimal repro repo if useful.
